'use strict';
const GATE='shlav-internal-hebrew', ACCESS='hebrew-access-v1', STORE='hebrew-practice-v1';
let unlocked=false;try{const key=new URL(location.href).searchParams.get('internal');if(key) localStorage.setItem(ACCESS,key);unlocked=localStorage.getItem(ACCESS)===GATE}catch(e){};
const app=document.getElementById('app'),langEl=document.getElementById('lang');
const UI={
he:{subtitle:'הבנה · הבעה · לשון',eyebrow:'לומדים בקצב שלך',headline:'עברית, צעד אחרי צעד.',intro:'קוראים קטע קצר, מבינים מילה, בונים משפט. אפשר לקבל רמז, להאזין ולנסות שוב. בלי שעון, בלי לחץ.',stage:'לאיזה שלב לומדים?',middle:'חטיבת ביניים',middleDesc:'קוראים, כותבים ומכירים את מבנה המשפט',high:'תיכון ובגרות',highDesc:'הבנה, הבעה ולשון · שאלונים 281 / 282',olim:'עברית לעולים',olimDesc:'עברית מעשית ושאלון 274 · רמה ג',how:'מה עושים עכשיו?',practiceDesc:'הבנת הנקרא ולשון · שלוש רמות · משוב מידי',conceptDesc:'מושגים קצרים עם דוגמה ותרגום',writeDesc:'כתיבה קצרה עם שאלות לבדיקה עצמית',tools:'כלי העזר שכבר באתר',ulpan:'אולפן: עברית שימושית',ulpanDesc:'אותיות, מילים, שלטים וטפסים בהקראה',kotvim:'כותבים ביחד',kotvimDesc:'פיגום לחיבור, מייל וסיפור',reader:'מקריא קולי',readerDesc:'ניקוד והקראה של כל טקסט עברי',exam:'תרגול עצמאי, לא שאלון רשמי. כדאי שמורה לעברית תבדוק לפני שימוש בכיתה.',level:'רמה',all:'כל הנושאים',question:'שאלה',outof:'מתוך',writingPrompt:'הטיוטה שלך',selfcheck:'בדיקה עצמית',check1:'עניתי על כל חלקי המשימה',check2:'כתבתי משפטים קצרים וברורים',check3:'בדקתי התאמה בין מילים, כתיב וסימני פיסוק',check4:'הבדלתי בין טענה, נימוק ודוגמה',none:'אין שאלות בבחירה הזאת. נסו נושא או רמה אחרים.',done:'ענית נכון על',retry:'עוד סבב',words:'מילים',empty:'לא הצלחתי לטעון את השאלות. נסו לרענן את הדף.',tutor:'עזרה מהמורה',speakPassage:'הקרא את הקטע',notSaved:'אין ציון אוטומטי. הטקסט נשאר בדפדפן עד סגירת הדף.',conceptIntro:'מושגים ממאגר הלשון. המונח וההגדרה בעברית תמיד גלויים.',sources:'מקורות לתיחום המסלולים',track:'מסלול',saved:'שאלות נענו בדפדפן הזה',plan:'תוכנית כתיבה',review:'בדקו בעצמכם',task:'משימה'},
ar:{subtitle:'فهم · تعبير · قواعد',eyebrow:'تعلّم حسب وتيرتك',headline:'العبرية، خطوة بخطوة.',intro:'اقرأ نصًا قصيرًا، افهم كلمة وابنِ جملة. يمكنك طلب تلميح أو الاستماع والمحاولة مجددًا. بلا توقيت أو ضغط.',stage:'لأي مرحلة تتعلم؟',middle:'المرحلة الإعدادية',middleDesc:'قراءة وكتابة وبنية الجملة',high:'الثانوية والبجروت',highDesc:'فهم وتعبير وقواعد · النموذجان 281 / 282',olim:'العبرية للوافدين الجدد',olimDesc:'عبرية عملية والنموذج 274 · المستوى ج',how:'ماذا نتمرّن الآن؟',practiceDesc:'فهم المقروء والقواعد · ثلاثة مستويات · ملاحظات فورية',conceptDesc:'مفاهيم قصيرة مع مثال وترجمة',writeDesc:'كتابة قصيرة مع قائمة مراجعة ذاتية',tools:'أدوات المساعدة الموجودة في الموقع',ulpan:'الأولبان: عبرية عملية',ulpanDesc:'حروف وكلمات ولافتات واستمارات مسموعة',kotvim:'نكتب معًا',kotvimDesc:'خطوات لكتابة موضوع أو بريد أو قصة',reader:'القارئ الصوتي',readerDesc:'تشكيل وقراءة أي نص عبري',exam:'هذا تدريب مستقل لا امتحان رسمي. يُنصح بمراجعة المعلّم قبل استخدامه في الصف.',level:'المستوى',all:'كل المواضيع',question:'السؤال',outof:'من',writingPrompt:'مسودتك',selfcheck:'مراجعة ذاتية',check1:'أجبت عن كل أجزاء المهمة',check2:'كتبت جملًا قصيرة وواضحة',check3:'راجعت المطابقة والإملاء وعلامات الترقيم',check4:'فرّقت بين الادعاء والسبب والمثال',none:'لا توجد أسئلة لهذا الاختيار. اختر موضوعًا أو مستوى آخر.',done:'إجابات صحيحة:',retry:'جولة أخرى',words:'كلمة',empty:'تعذر تحميل الأسئلة. حدّث الصفحة.',tutor:'مساعدة المعلّمة',speakPassage:'قراءة النص',notSaved:'لا يوجد تقييم آلي. يبقى النص في المتصفح حتى إغلاق الصفحة.',conceptIntro:'مفاهيم من بنك القواعد. المصطلح والتعريف العبريان ظاهران دائمًا.',sources:'مصادر تقسيم المسارات',track:'المسار',saved:'إجابات في هذا المتصفح',plan:'خطة الكتابة',review:'راجِع بنفسك',task:'مهمة'},
ru:{subtitle:'Понимание · письмо · грамматика',eyebrow:'Учитесь в своём темпе',headline:'Иврит, шаг за шагом.',intro:'Читайте короткий текст, разбирайте слова и стройте фразы. Подсказки и озвучивание без таймера и спешки.',stage:'Для какого уровня?',middle:'Средняя школа',middleDesc:'Чтение, письмо и структура предложения',high:'Старшая школа и багрут',highDesc:'Понимание, письмо и грамматика · 281 / 282',olim:'Иврит для репатриантов',olimDesc:'Практический иврит и экзамен 274 · уровень Г',how:'Что будем делать?',practiceDesc:'Чтение и грамматика · три уровня · объяснения',conceptDesc:'Краткие понятия с примерами и переводом',writeDesc:'Короткий текст с самопроверкой',tools:'Другие инструменты сайта',ulpan:'Ульпан: разговорный иврит',ulpanDesc:'Буквы, слова, вывески и формы с озвучкой',kotvim:'Пишем вместе',kotvimDesc:'Пошаговое сочинение, письмо или рассказ',reader:'Читалка',readerDesc:'Огласовка и чтение любого текста на иврите',exam:'Самостоятельная практика, не официальный экзамен. Перед применением в классе нужна проверка учителем.',level:'Уровень',all:'Все темы',question:'Вопрос',outof:'из',writingPrompt:'Ваш черновик',selfcheck:'Самопроверка',check1:'Я ответил на все части задания',check2:'Написал ясные короткие предложения',check3:'Проверил согласование, орфографию и пунктуацию',check4:'Отличил тезис от довода и примера',none:'Нет вопросов для этого выбора. Попробуйте другую тему или уровень.',done:'Правильных ответов:',retry:'Ещё раз',words:'слов',empty:'Не удалось загрузить вопросы. Обновите страницу.',tutor:'Помощь преподавателя',speakPassage:'Прочитать текст',notSaved:'Автоматической оценки нет. Черновик исчезнет после закрытия вкладки.',conceptIntro:'Понятия из банка грамматики. Термин и определение на иврите всегда видны.',sources:'Источники для разделения программ',track:'Трек',saved:'Ответов в этом браузере',plan:'План письма',review:'Проверьте себя',task:'Задание'},
en:{subtitle:'Reading · writing · language',eyebrow:'Learn at your own pace',headline:'Hebrew, one step at a time.',intro:'Read a short passage, understand a word, and build a sentence. Use a hint, listen, or try again. No timer, no pressure.',stage:'Which level are you learning?',middle:'Middle school',middleDesc:'Reading, writing, and sentence structure',high:'High school and bagrut',highDesc:'Reading, writing, and grammar · papers 281 / 282',olim:'Hebrew for new immigrants',olimDesc:'Practical Hebrew and paper 274 · level C',how:'What would you like to do?',practiceDesc:'Reading and grammar · three levels · instant feedback',conceptDesc:'Short terms with examples and translations',writeDesc:'Short writing with a self-review checklist',tools:'Existing tools on the site',ulpan:'Ulpan: practical Hebrew',ulpanDesc:'Letters, words, signs, and forms with audio',kotvim:'Write together',kotvimDesc:'Step-by-step essay, email, or story',reader:'Text reader',readerDesc:'Vowel marks and audio for any Hebrew text',exam:'Independent practice, not an official exam. A teacher should check it before classroom use.',level:'Level',all:'All topics',question:'Question',outof:'of',writingPrompt:'Your draft',selfcheck:'Self-review',check1:'I answered every part of the prompt',check2:'I wrote short, clear sentences',check3:'I checked agreement, spelling, and punctuation',check4:'I separated claims, reasons, and examples',none:'No questions for this selection. Try another level or topic.',done:'Correct answers:',retry:'Another round',words:'words',empty:'Could not load the questions. Please refresh.',tutor:'Ask the teacher',speakPassage:'Read the passage',notSaved:'There is no automatic grade. The draft disappears when you close the page.',conceptIntro:'Terms from the grammar bank. The Hebrew term and definition remain visible.',sources:'Track sources',track:'Track',saved:'Answers on this browser',plan:'Writing plan',review:'Self-review',task:'Task'}};
const U=k=>UI[lang][k];
const LABEL={he:{choose:'בחרו מסלול',practice:'תרגול קצר',concept:'דף מושגים',write:'כתיבה מודרכת',listen:'הקרא',stopB:'עצירה',hint:'רמז',next:'לשאלה הבאה',again:'נכון, יפה!',wrong:'עוד רגע של חשיבה',end:'סיימת סבב',back:'חזרה למסלולים'},ar:{choose:'اختر المسار',practice:'تدريب قصير',concept:'بطاقات مفاهيم',write:'تدريب كتابة',listen:'استمع',stopB:'إيقاف',hint:'تلميح',next:'السؤال التالي',again:'صحيح!',wrong:'لنحاول من جديد',end:'انتهى التدريب',back:'العودة للمسارات'},ru:{choose:'Выберите трек',practice:'Практика',concept:'Словарь',write:'Письмо',listen:'Прослушать',stopB:'Стоп',hint:'Подсказка',next:'Следующий вопрос',again:'Верно!',wrong:'Попробуйте еще',end:'Раунд окончен',back:'Назад'},en:{choose:'Choose a track',practice:'Short practice',concept:'Concept sheet',write:'Guided writing',listen:'Read aloud',stopB:'Stop',hint:'Hint',next:'Next question',again:'Correct!',wrong:'Try again',end:'Round complete',back:'Back to tracks'}};
let lang='he',stage='high',track='281',view='home',level=1,topic='all',bank=null,round=[],idx=0,chosen=-1,showHint=false,score=0,writing='',writingTask=0;
let progress={answered:0,correct:0};try{progress=Object.assign(progress,JSON.parse(localStorage.getItem(STORE)||'{}'))}catch(e){};
function t(x){return x&&typeof x==='object'?(x[lang]||x.he||''):x||''}function safe(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}const esc=x=>safe(t(x));const L=k=>LABEL[lang][k];const V_F=/(הילה|כרמית|زارية|سلمى|أمينة|امينة|هدى|فاطمة|ليلى|نورا|светлана|дарья|ирина|екатерина|татьяна|елена|female|woman|#female|\bfem\b|carmit|hila|\bmiri\b|\bdana\b|shira|samantha|karen|moira|tessa|serena|victoria|\bava\b|allison|susan|vicki|nicky|\bzoe\b|fiona|\bkate\b|shelley|zira|hazel|aria|jenny|michelle|\bana\b|\beva\b|emma|libby|sonia|natasha|clara|\bamber\b|ashley|\bcora\b|elizabeth|monica|\bsara\b|\bsarah\b|\bjane\b|\bnancy\b|\bluna\b|\bmolly\b|irina|milena|svetlana|dariya|\belena\b|katja|ekaterina|\bkatya\b|tatyana|\balena\b|hoda|salma|zariyah|amina|\bhala\b|noura|laila|layla|fatima|zeina|\biman\b|\brana\b|\bsana\b|maryam|asma|heera|raveena|swara|neerja)/;
const V_M=/(אברי|אסף|حامد|ماجد|طارق|ناصر|بسام|дмитрий|павел|юрий|максим|николай|google[^a-z]{0,15}(arabic|العربية)|\bmale\b|\bman\b|#male|asaf|avri|yoni|moshe|\balex\b|daniel|\bfred\b|\btom\b|aaron|arthur|oliver|rishi|gordon|\blee\b|ralph|bruce|david|\bmark\b|\bguy\b|ryan|christopher|\beric\b|brian|andrew|roger|steffan|liam|william|george|james|\bthomas\b|benjamin|brandon|\bjason\b|\btony\b|dmitry|pavel|\byuri\b|artemi|maxim|nikolai|maged|tarik|naayf|hamed|shakir|\bomar\b|tarek|\bali\b|bassel|\bmoaz\b|hamdan|saleh|abdullah|\btaim\b|fahed|rakan|yasser|hemant|madhur|prabhat)/;
const vGender=v=>{const n=((v.name||'')+' '+(v.lang||'')).toLowerCase();return V_F.test(n)?'f':V_M.test(n)?'m':'?'};
const TTS_CODE={he:'he-IL',ar:'ar-SA',ru:'ru-RU',en:'en-US'};
const FEM_PITCH=1.35;
/* בחירת קול: נשי תחילה (סטנדרט civics), אחר כך לא-מזוהה, ורק אז מה שיש.
   קול שזוהה כגברי מקבל הרמת גובה, כי בדפדפן אין דרך אחרת. */
const pickVoice=lg=>{const base=TTS_CODE[lg].split('-')[0];const all=speechSynthesis.getVoices()||[];if(!all.length)return{empty:true};const pool=all.filter(v=>(v.lang||'').replace('_','-').toLowerCase().split('-')[0]===base);if(!pool.length)return{none:true};return{v:pool.find(v=>vGender(v)==='f')||pool.find(v=>vGender(v)==='?')||pool[0]}};
const VNOTICE={he:'אין במכשיר קול בשפה {L}, לכן החלק הזה לא מוקרא',ar:'لا يوجد على الجهاز صوت باللغة {L}، لذا لا تُقرأ هذه الفقرة',ru:'На устройстве нет голоса для языка {L}, поэтому этот фрагмент не озвучивается',en:'This device has no {L} voice, so this part is not read aloud'};
const VLNAME={he:{ar:'ערבית',ru:'רוסית',en:'אנגלית'},ar:{ar:'العربية',ru:'الروسية',en:'الإنجليزية'},ru:{ar:'арабского',ru:'русского',en:'английского'},en:{ar:'Arabic',ru:'Russian',en:'English'}};
const vNotice=miss=>{const msg=(VNOTICE[lang]||VNOTICE.he).replace('{L}',(VLNAME[lang]||VLNAME.he)[miss]||miss);let d=document.getElementById('vnotice');if(!d){d=document.createElement('div');d.id='vnotice';d.style.cssText='position:fixed;bottom:1rem;inset-inline-start:50%;transform:translateX(50%);background:#5b4a00;color:#fff;padding:.6rem 1rem;border-radius:10px;font-size:.9rem;z-index:60;box-shadow:0 4px 14px #0004';document.body.appendChild(d)}d.textContent=msg;d.style.display='block';clearTimeout(d._t);d._t=setTimeout(()=>{d.style.display='none'},4500)};
let _sg=0;
/* הקראה שמכבדת את שפת הטקסט: כל חלק מוקרא בקול של שפתו, נשי תחילה.
   חלק בשפה שאין לה קול במכשיר לא נקרא בקול עברי — מוצגת הודעה. */
const speakParts=parts=>{if(!window.speechSynthesis)return;speechSynthesis.cancel();const my=++_sg;parts=parts.filter(p=>p.text&&String(p.text).trim());const step=i=>{if(my!==_sg||i>=parts.length)return;const p=parts[i],code=TTS_CODE[p.lg]||TTS_CODE.he,r=pickVoice(p.lg);if(r.none&&!r.empty){if(p.lg!=='he'){vNotice(p.lg);step(i+1);return}}const u=new SpeechSynthesisUtterance(String(p.text));u.lang=code;u.rate=.83;if(r.v){u.voice=r.v;u.pitch=vGender(r.v)==='m'?FEM_PITCH:1}u.onend=()=>step(i+1);u.onerror=()=>step(i+1);speechSynthesis.speak(u)};step(0)};
const speak=(s,lg)=>speakParts([{text:s,lg:lg||'he'}]);
/* זיהוי שפה מהכתב בפועל — שדה תרגום יכול להכיל עברית (fallback ב-data). */
const textLang=s=>{s=String(s||'');const c={he:(s.match(/[\u0590-\u05FF]/g)||[]).length,ar:(s.match(/[\u0600-\u06FF]/g)||[]).length,ru:(s.match(/[\u0400-\u04FF]/g)||[]).length,en:(s.match(/[A-Za-z]/g)||[]).length};return Object.keys(c).reduce((a,b)=>c[b]>c[a]?b:a,'he')};
function setLang(v){lang=LABEL[v]?v:'he';langEl.value=lang;document.documentElement.lang=lang;document.documentElement.dir=['ar','he'].includes(lang)?'rtl':'ltr';document.querySelector('header .mini').textContent=U('subtitle');document.querySelector('#lang-label').textContent=({he:'שפת העזר',ar:'لغة المساعدة',ru:'Язык подсказок',en:'Help language'})[lang];document.querySelector('#footer').textContent=U('exam');render()}langEl.onchange=e=>setLang(e.target.value);
function base(content){app.innerHTML=content+`<div class="sources">${U('sources')}: <a target="_blank" rel="noopener" href="https://pop.education.gov.il/tchumey_daat/ivrit_havana_habaa_lashon/chativat-beynayim/noseem_nilmadim/havana_habaa/">חטיבת ביניים</a> · <a target="_blank" rel="noopener" href="https://pop.education.gov.il/tchumey_daat/ivrit_havana_habaa_lashon/chativa-elyona/bhinot-bagrut-umesimot/">שאלונים 281/282</a> · <a target="_blank" rel="noopener" href="https://pop.education.gov.il/tchumey_daat/ivrit_havana_habaa_lashon/chativa-elyona/havana-habaa-olim/matriculation-questionnaires-274/">שאלון 274</a>. ${U('exam')}</div>`}
function home(){base(`<section class="hero"><div><div class="eyebrow">${U('eyebrow')}</div><h1>${U('headline')}</h1><p>${U('intro')}</p></div><div class="hero-art" aria-hidden="true">א</div></section><h2>${U('stage')}</h2><div class="tracks">${[['middle','middle','middleDesc'],['high','high','highDesc'],['olim','olim','olimDesc']].map(([id,name,desc])=>`<button class="card track ${stage===id?'active':''}" data-stage="${id}" aria-pressed="${stage===id}"><span class="num">${id==='middle'?'7–9':id==='high'?'10–12':'ע'}</span><strong>${U(name)}</strong><small>${U(desc)}</small></button>`).join('')}</div>${stage==='high'?`<div class="bar" style="margin-top:15px"><button class="pill ${track==='281'?'active':''}" data-track="281">281 · 70%</button><button class="pill ${track==='282'?'active':''}" data-track="282">282 · 30%</button></div>`:''}<h2>${U('how')}</h2><div class="tiles"><button class="card tile" data-view="practice"><span class="glyph">◉</span><strong>${L('practice')}</strong><small>${U('practiceDesc')}</small></button><button class="card tile" data-view="concept"><span class="glyph">▤</span><strong>${L('concept')}</strong><small>${U('conceptDesc')}</small></button><button class="card tile" data-view="write"><span class="glyph">✎</span><strong>${L('write')}</strong><small>${U('writeDesc')}</small></button></div><h2>${U('tools')}</h2><div class="tiles">${[['ulpan','ulpan','ulpanDesc'],['kotvim','kotvim','kotvimDesc'],['reader','reader','readerDesc']].map(([path,name,desc])=>`<a class="card tile" href="/${path}/" style="text-decoration:none"><span class="glyph">↗</span><strong>${U(name)}</strong><small>${U(desc)}</small></a>`).join('')}</div><div class="note">${U('exam')}</div><p class="status">${progress.answered} ${U('saved')}</p>`)}

const custom=[
{tracks:['281','274'],topic:'הבנת הנקרא',level:1,passage:'בספרייה השכונתית נפתח מדף להחלפת ספרים. כל תושב יכול להניח ספר במצב טוב ולקחת ספר אחר. פעם בשבוע מתנדבים מסדרים את המדף.',prompt:'מה יכולים התושבים לעשות במדף החדש?',options:['להחליף ספרים','לקנות מחברות','להירשם לשיעור','לשאול מחשב'],correct:0,hint:'חפשו בטקסט את הפועל שליד המילה ספרים.',explain:'המדף נועד להחלפת ספרים: מניחים ספר ולוקחים ספר אחר.'},
{tracks:['281','274'],topic:'הבנת הנקרא',level:2,passage:'בספרייה השכונתית נפתח מדף להחלפת ספרים. כל תושב יכול להניח ספר במצב טוב ולקחת ספר אחר. פעם בשבוע מתנדבים מסדרים את המדף.',prompt:'למה המתנדבים מסדרים את המדף בכל שבוע?',options:['כדי שהספרים יהיו נגישים ומסודרים','כדי למכור את הספרים','כי הספרייה סגורה','כדי להחליף את המבנה'],correct:0,hint:'חשבו מה קורה למדף שמשתמשים בו רבים.',explain:'הטקסט מציין שהם מסדרים אותו; הסיבה הסבירה היא לשמור על סדר ונגישות. זו הסקה, לא ציטוט מפורש.'},
{tracks:['281','274'],topic:'הבנת הנקרא',level:3,passage:'עיריית נחלון הוסיפה שביל הליכה ליד בית הספר. לפי הודעתה, השביל מיועד להקל על ההגעה ברגל. כמה הורים ביקשו גם הצללה, משום שבצהריים השביל חשוף לשמש.',prompt:'איזה משפט מבדיל בין עובדה לדעה?',options:['העירייה הוסיפה שביל; ההצללה היא בקשה של חלק מההורים','כל ההורים מרוצים מהשביל','השביל מסוכן בכל שעות היום','העירייה כבר בנתה הצללה'],correct:0,hint:'מה כבר קרה, ומה רק התבקש?',explain:'הוספת השביל היא עובדה המתוארת בקטע; הצללה היא בקשה שטרם נאמר שבוצעה.'},
{tracks:['282','281'],topic:'כתיבה וטיעון',level:1,prompt:'איזה משפט מתאים לפתיחה של טיעון על קריאה יומית?',options:['לדעתי, כדאי לקרוא בכל יום מפני שהדבר מרחיב את אוצר המילים.','מחר השעה ארבע ירוקה.','קריאה יומית. קריאה יומית.','אבל לכן הספרייה.'],correct:0,hint:'טענה טובה מציגה עמדה וגם סיבה.',explain:'המשפט מציג עמדה ומנמק אותה.'},
{tracks:['282','281'],topic:'כתיבה וטיעון',level:2,prompt:'איזו מילת קישור מציינת ניגוד?',options:['אולם','מפני ש','לכן','למשל'],correct:0,hint:'חפשו מילה שמקשרת בין שני רעיונות שונים או מנוגדים.',explain:'אולם מציינת ניגוד. מפני ש - סיבה; לכן - תוצאה; למשל - דוגמה.'},
{tracks:['282','281'],topic:'כתיבה וטיעון',level:3,prompt:'מה חשוב לעשות כשמשלבים מידע ממקור אחר בסיכום?',options:['לציין מאין המידע ולהבדיל בינו לבין דברי הכותב','להעתיק בלי לציין מקור','לשנות מספרים כדי שייראו מקוריים','להוסיף עובדות שלא הופיעו'],correct:0,hint:'הקורא צריך לדעת מי אמר מה.',explain:'ייחוס למקור והבחנה בין מידע לבין פרשנות משמרים את מהימנות הכתיבה.'},
{tracks:['274'],topic:'עברית לעולים',level:1,prompt:'איזה משפט מתאים לתיאור פעולה שהתרחשה אתמול?',options:['אתמול קראתי ספר.','מחר קראתי ספר.','עכשיו קראתי ספר.','אתמול אקרא ספר.'],correct:0,hint:'אתמול מתאים לצורת עבר.',explain:'קראתי היא צורת עבר המתאימה לאתמול.'},
{tracks:['274'],topic:'עברית לעולים',level:2,prompt:'השלימו: הילדים ___ לספרייה בכל יום.',options:['הולכים','הולכת','הולך','הלך'],correct:0,hint:'ילדים הם רבים, זכר.',explain:'הולכים מתאים לזכר רבים בזמן הווה.'},
{tracks:['274'],topic:'עברית לעולים',level:3,prompt:'איזה משפט מציג סיבה ותוצאה?',options:['ירד גשם, ולכן נשארנו בבית.','ירד גשם, אבל השולחן כחול.','גשם ספרייה אתמול.','נשארנו בבית, למשל ולכן.'],correct:0,hint:'המילה לכן מסמנת מה קרה בעקבות הסיבה.',explain:'הגשם הוא הסיבה; ההישארות בבית היא התוצאה.'}
];
function seedQuestions(){let q=[];for(const group of bank.topics){for(let lv=0;lv<3;lv++){let pool=group.levels[lv].filter(x=>x.type==='concept');for(let i=0;i<pool.length;i++){const c=pool[i];const wrong=[1,2,3].map(step=>pool[(i+step)%pool.length].def);q.push({tracks:group.id==='lsh-parts'?['281','282','274']:['281','282','274'],topic:group.name.he,level:lv+1,prompt:{he:`מה משמעות המושג ״${c.name.he}״?`,ar:`ما معنى المصطلح العبري «${c.name.he}» (${c.name.ar})؟`,ru:`Что означает «${c.name.he}» (${c.name.ru})?`,en:`What does «${c.name.he}» (${c.name.en}) mean?`},options:[c.def,...wrong],correct:0,hint:{he:`נסו לחשוב על דוגמה ל-${c.name.he}.`,ar:`فكروا في مثال على ${c.name.ar}.`,ru:`Подумайте о примере: ${c.name.ru}.`,en:`Think of an example of ${c.name.en}.`},explain:Object.fromEntries(['he','ar','ru','en'].map(z=>[z,`${c.name[z]||c.name.he}: ${c.def[z]||c.def.he}`]))})}for(const sc of group.levels[lv].filter(x=>x.type==='scenario')){for(const s of sc.questions.flat()){q.push({tracks:['281','274'],topic:group.name.he,level:lv+1,passage:sc.lines.he.join(' '),prompt:s.prompt,options:[s.answer,...s.wrong],correct:0,hint:'חזרו למשפט בקטע שעוסק בשאלה.',explain:s.answer})}}}}return q.concat(custom,bank.practice||[])}
function shuffle(a){let b=[...a];for(let i=b.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b}function buildRound(){let all=seedQuestions().filter(q=>(stage==='middle'?q.tracks.includes('middle'):q.tracks.includes(track))&&q.level===level&&(topic==='all'||q.topic===topic));round=shuffle(all).slice(0,Math.min(8,all.length)).map(q=>({...q,choices:shuffle(q.options)}));idx=0;chosen=-1;showHint=false;score=0}
function practice(){const topics=[...new Set(seedQuestions().filter(q=>(stage==='middle'?q.tracks.includes('middle'):q.tracks.includes(track))&&q.level===level).map(q=>q.topic))];let nav=`<button class="back" data-view="home">← ${L('back')}</button><div class="bar"><span class="tag">${stage==='middle'?U('middle'):U('track')+' '+track}</span>${[1,2,3].map(n=>`<button class="pill ${n===level?'active':''}" data-level="${n}">${U('level')} ${n}</button>`).join('')}<select id="topic" aria-label="נושא"><option value="all">${U('all')}</option>${topics.map(x=>`<option value="${safe(x)}" ${x===topic?'selected':''}>${safe(x)}</option>`).join('')}</select></div>`;if(!round.length){base(nav+`<div class="error">${U('none')}</div>`);return}if(idx>=round.length){base(nav+`<section class="card practice"><h2>${L('end')}</h2><p>${U('done')} ${score} ${U('outof')} ${round.length}.</p><button class="primary" data-action="restart">${U('retry')}</button></section>`);return}let q=round[idx],selected=chosen>=0,correctIndex=q.choices.indexOf(q.options[q.correct]);base(nav+`<section class="card practice"><div class="status">${U('question')} ${idx+1} ${U('outof')} ${round.length} · ${safe(q.topic)}</div><div class="progress" aria-hidden="true"><span style="width:${(idx/round.length)*100}%"></span></div>${q.passage?`<div class="passage" dir="rtl">${safe(q.passage)}</div>`:''}<h2 class="question-title" dir="rtl">${esc(q.prompt)}</h2><div class="controls">${q.passage?`<button class="secondary" data-action="speak-passage">🔊 ${U('speakPassage')}</button>`:''}<button class="secondary" data-action="speak">🔊 ${L('listen')}</button><button class="secondary" data-action="hint">${L('hint')}</button>${`<button class="secondary" data-action="tutor">${U('tutor')}</button>`}<button class="secondary" data-action="stop">${L('stopB')}</button></div>${showHint?`<div class="note">${esc(q.hint)}</div>`:''}<div class="options">${q.choices.map((a,i)=>`<button class="answer ${selected?(i===correctIndex?'correct':i===chosen?'wrong':''):''}" data-answer="${i}" ${selected?'disabled':''}>${esc(a)}</button>`).join('')}</div>${selected?`<div role="status" class="feedback ${chosen===correctIndex?'':'bad'}"><strong>${chosen===correctIndex?L('again'):L('wrong')}</strong><div>${esc(q.explain)}</div></div><button class="primary" data-action="next">${L('next')}</button>`:''}</section>`)}
function concept(){let all=bank.topics.flatMap(g=>g.levels.flat().filter(x=>x.type==='concept').map(x=>({name:x.name,def:x.def,topic:g.name.he})));let relevant=(bank.conceptExtras||[]).filter(x=>stage==='middle'?['הבנת הנקרא','תחביר','מערכת הצורות','כתיבה וטיעון'].includes(x.topic):track==='274'?['עברית לעולים','הבנת הנקרא','כתיבה וטיעון'].includes(x.topic):true);let items=[...relevant,...all];base(`<button class="back" data-view="home">← ${L('back')}</button><h1>${L('concept')}</h1><p class="section-lead">${U('conceptIntro')}</p><div class="concepts">${items.map(x=>`<article><small class="tag">${safe(x.topic)}</small><strong dir="rtl">${safe(x.name.he)}</strong><p dir="rtl">${safe(x.def.he)}</p>${lang!=='he'?`<div class="translation" dir="auto">${esc(x.name)}: ${esc(x.def)}</div>`:''}<button class="secondary" data-say="${safe(x.name.he)}" aria-label="הקרא ${safe(x.name.he)}">🔊</button></article>`).join('')}</div>`)}
function writeView(){let tasks=bank.writing[stage==='middle'?'middle':track],w=tasks[writingTask%tasks.length];base(`<button class="back" data-view="home">← ${L('back')}</button><section class="card practice"><span class="tag">${stage==='middle'?U('middle'):U('track')+' '+track}</span><h1>${L('write')}</h1><div class="bar">${tasks.map((_,i)=>`<button class="pill ${i===writingTask?'active':''}" data-writing="${i}">${U('task')} ${i+1}</button>`).join('')}</div><p dir="rtl">${safe(w.prompt)}</p><div class="note" dir="rtl"><strong>${U('plan')}:</strong> ${safe(w.plan)}</div><div class="note">${U('notSaved')}</div><label for="draft">${U('writingPrompt')}</label><textarea id="draft" dir="rtl" placeholder="אפשר להתחיל במשפט קצר..."></textarea><p id="wordcount" class="status">0 ${U('words')}</p><div class="controls"><button class="secondary" data-action="speak-prompt">🔊 ${L('listen')}</button><button class="secondary" data-action="stop">${L('stopB')}</button></div><h2>${U('selfcheck')}</h2><p dir="rtl">${safe(w.check)}</p><div class="checks"><label><input type="checkbox"> ${U('check1')}</label><label><input type="checkbox"> ${U('check2')}</label><label><input type="checkbox"> ${U('check3')}</label>${track==='281'?`<label><input type="checkbox"> ${U('check4')}</label>`:''}</div></section>`);document.getElementById('draft').value=writing;updateWords()}
function updateWords(){let d=document.getElementById('draft');if(d)document.getElementById('wordcount').textContent=`${d.value.trim()?d.value.trim().split(/\s+/).length:0} ${U('words')}`}
function render(){if(!unlocked){app.innerHTML='<div class="error"><h1>דף פנימי</h1><p>הגרסה הזאת עדיין אינה פתוחה לציבור.</p></div>';return}if(!bank){app.innerHTML='<div class="card">טוענים...</div>';return}if(view==='practice')practice();else if(view==='concept')concept();else if(view==='write')writeView();else home()}
app.addEventListener('input',e=>{if(e.target.id==='draft'){writing=e.target.value;updateWords()}});app.addEventListener('change',e=>{if(e.target.id==='topic'){topic=e.target.value;buildRound();render()}});
app.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.stage){stage=b.dataset.stage;track=stage==='olim'?'274':'281';level=1;topic='all';round=[];render();return}if(b.dataset.track){track=b.dataset.track;topic='all';round=[];render();return}if(b.dataset.view){view=b.dataset.view;round=[];if(view==='practice')buildRound();if(view==='write'){writingTask=0;writing=''}render();return}if(b.dataset.writing){writingTask=Number(b.dataset.writing);writing='';render();return}if(b.dataset.level){level=Number(b.dataset.level);buildRound();render();return}if(b.dataset.say){speak(b.dataset.say,'he');return}let a=b.dataset.action,q=round[idx];if(a==='restart'){buildRound();render()}else if(a==='speak'){const pt=t(q.prompt);speakParts([{text:q.passage,lg:'he'},{text:pt,lg:textLang(pt)}])}else if(a==='speak-passage')speak(q.passage,'he');else if(a==='speak-prompt')speak(bank.writing[stage==='middle'?'middle':track][writingTask].prompt,'he');else if(a==='hint'){showHint=true;render()}else if(a==='next'){idx++;chosen=-1;showHint=false;render()}else if(a==='tutor'&&q){showHint=true;render();let note=document.querySelector('.practice .note');if(note)note.textContent=t(q.hint)}else if(a==='stop'){try{speechSynthesis.cancel()}catch(e){}}});
app.addEventListener('click',e=>{let b=e.target.closest('[data-answer]');if(!b||chosen>=0)return;chosen=Number(b.dataset.answer);let q=round[idx];if(q.choices[chosen]===q.options[q.correct])score++;progress.answered++;progress.correct+=Number(q.choices[chosen]===q.options[q.correct]);try{localStorage.setItem(STORE,JSON.stringify(progress))}catch(e){}render()});
fetch('bank.json').then(r=>{if(!r.ok)throw Error('bank');return r.json()}).then(data=>{bank=data;render()}).catch(()=>{app.innerHTML='<div class="error">'+U('empty')+'</div>'});render();
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
